### ISSUE TITLE
Ensure responsive styles (v2)

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#64]

**Comment by tmfrnz** [comment]
It appears that the latest css updates are breaking the layout for mobile devices (<768px)

**Comment by rdoc101** [comment]
Fixed the breaking of the layout.

**Comment by tmfrnz** [comment]
Issues persist at least for 
- secondary menu 
- primary navigation - should have shortened titles
- category view - spacing (used to have a div role="main" wrapped around the div role="article")
- intro page header (no layout yet provided)
- intro page category buttons should have same height
- intro page "all" buttons should stay in one line
